name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
        
      - name: Install Dependencies
        run: poetry install

      - name: Setup PyPI token
        run: poetry config pypi-token.pypi ${{secrets.PYPI_TOKEN}}

      - name: Publish to PyPI
        run: poetry publish -n --build
